--- #YAML:1.0
name:                PPIx-LineToSub
version:             0.32
abstract:            ~
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    PPI:                           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
